/**
 * Procedural NES-like pixel atlas for 红帽奇遇.
 * Original tribute art — not Nintendo tiles or characters.
 */

export const TILE = 16;

const PAL = {
  ".": null,
  R: "#e52521",
  r: "#9c1410",
  B: "#3d73c8",
  b: "#234a8c",
  S: "#f8c090",
  s: "#c88858",
  H: "#3a1f0a",
  N: "#6b3a1f",
  n: "#3d2110",
  W: "#fff8e8",
  Y: "#f8d030",
  y: "#c89010",
  G: "#3cb043",
  g: "#1e7a28",
  K: "#1a1208",
  O: "#fc9838",
  o: "#c86818",
  P: "#f878a0",
  C: "#5c94fc",
  U: "#203060",
  D: "#5a5a5a",
  d: "#2e2e2e",
  L: "#d05020",
  A: "#a0e0ff",
  M: "#8b5a2b",
  m: "#c48a3a",
  T: "#70c8f8",
  F: "#f0e0b0",
  E: "#e8b060",
  Z: "#90f060",
  X: "#201818",
  I: "#d8f0ff",
  i: "#88c0e0",
};

function canvas(w, h) {
  const c = document.createElement("canvas");
  c.width = w;
  c.height = h;
  const ctx = c.getContext("2d");
  ctx.imageSmoothingEnabled = false;
  return { c, ctx };
}

function paint(str, pal = PAL) {
  const rows = str.trim().split("\n").map((l) => l.trim());
  const h = rows.length;
  const w = Math.max(...rows.map((r) => r.length));
  const { c, ctx } = canvas(w, h);
  for (let y = 0; y < h; y++) {
    const row = rows[y];
    for (let x = 0; x < row.length; x++) {
      const col = pal[row[x]];
      if (!col) continue;
      ctx.fillStyle = col;
      ctx.fillRect(x, y, 1, 1);
    }
  }
  return c;
}

function recolor(src, map) {
  const { c, ctx } = canvas(src.width, src.height);
  ctx.drawImage(src, 0, 0);
  const img = ctx.getImageData(0, 0, src.width, src.height);
  const d = img.data;
  for (let i = 0; i < d.length; i += 4) {
    if (d[i + 3] < 8) continue;
    const key = `${d[i]},${d[i + 1]},${d[i + 2]}`;
    const next = map[key];
    if (!next) continue;
    d[i] = next[0];
    d[i + 1] = next[1];
    d[i + 2] = next[2];
  }
  ctx.putImageData(img, 0, 0);
  return c;
}

function hexRgb(hex) {
  const n = parseInt(hex.slice(1), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

const FIRE_MAP = {
  [`${hexRgb("#3d73c8")}`]: hexRgb("#fff8e8"),
  [`${hexRgb("#234a8c")}`]: hexRgb("#c8c0a8"),
  [`${hexRgb("#e52521")}`]: hexRgb("#fff8e8"),
  [`${hexRgb("#9c1410")}`]: hexRgb("#c8c0a8"),
};

function flipH(src) {
  const { c, ctx } = canvas(src.width, src.height);
  ctx.translate(src.width, 0);
  ctx.scale(-1, 1);
  ctx.drawImage(src, 0, 0);
  return c;
}

const HERO_S = {
  idle: `
....RRRRR.......
...RRRRRRRR.....
...HHHSSSH......
..HSHSSSHSS.....
..HSHSSSSHS.....
...SSSSSSS......
....HBBB........
...BBBBBB.......
..BBBRRBBB......
..BBRRRRBB......
...RRRRRR.......
...NN..NN.......
..NNN..NNN......
................
................
................
`,
  walk0: `
....RRRRR.......
...RRRRRRRR.....
...HHHSSSH......
..HSHSSSHSS.....
..HSHSSSSHS.....
...SSSSSSS......
....BBBB........
...BBBBBB.......
..BBBRRBBB......
..BBRRRRBB......
...RRRRRR.......
....NN.NN.......
....NNNNN.......
................
................
................
`,
  walk1: `
....RRRRR.......
...RRRRRRRR.....
...HHHSSSH......
..HSHSSSHSS.....
..HSHSSSSHS.....
...SSSSSSS......
....BBBB........
...BBBBBB.......
..BBBRRBBB......
..BBRRRRBB......
...RRRRRR.......
...NN...NN......
..NNN...NNN.....
................
................
................
`,
  jump: `
....RRRRR.......
...RRRRRRRR.....
...HHHSSSH......
..HSHSSSHSS.....
..HSHSSSSHS.....
...SSSSSSS......
..N.BBBB.N......
.NNBBBBBBNN.....
..BBBRRBBB......
..BBRRRRBB......
...RRRRRR.......
...NN...NN......
..NN.....NN.....
................
................
................
`,
  skid: `
.....RRRRR......
....RRRRRRRR....
....HHHSSSH.....
...HSHSSSHSS....
...HSHSSSSHS....
....SSSSSSS.....
.....BBBB.......
....BBBBBB......
...RRBBBBRR.....
...RRRRRRRR.....
....RRRRRR......
...NN....NN.....
..NNN....NNN....
................
................
................
`,
  die: `
................
....RRRRR.......
...RRRRRRRR.....
...SSSKKSS......
..SSSSSSSSS.....
...SSSSSSS......
....H.H.........
...BBBBBB.......
..BBRRRRBB......
..RRRRRRRR......
.NN......NN.....
NNN......NNN....
................
................
................
................
`,
};

const HERO_B = {
  idle: `
....RRRRRR......
...RRRRRRRRR....
...HHHSSSSH.....
..HSHSSSSHSS....
..HSHSSSSSHS....
...SSSSSSSS.....
....H...........
....BBBBBB......
...BBBBBBBB.....
..BBBBRRBBBB....
..BBBRRRRBBB....
..BBBRRRRBBB....
...BBRRRRBB.....
....RRRRRR......
....NN..NN......
...NNN..NNN.....
..NNNN..NNNN....
................
................
................
................
................
................
................
................
................
................
................
................
................
`,
  walk0: `
....RRRRRR......
...RRRRRRRRR....
...HHHSSSSH.....
..HSHSSSSHSS....
..HSHSSSSSHS....
...SSSSSSSS.....
....BBBBBB......
...BBBBBBBB.....
..BBBBRRBBBB....
..BBBRRRRBBB....
..BBBRRRRBBB....
...BBRRRRBB.....
....RRRRRR......
....NN.NN.......
...NNNNNN.......
..NNNN..........
................
................
................
................
................
................
................
................
................
................
................
................
................
`,
  walk1: `
....RRRRRR......
...RRRRRRRRR....
...HHHSSSSH.....
..HSHSSSSHSS....
..HSHSSSSSHS....
...SSSSSSSS.....
....BBBBBB......
...BBBBBBBB.....
..BBBBRRBBBB....
..BBBRRRRBBB....
..BBBRRRRBBB....
...BBRRRRBB.....
....RRRRRR......
...NN....NN.....
..NNN....NNN....
.NNNN....NNNN...
................
................
................
................
................
................
................
................
................
................
................
................
................
`,
  jump: `
....RRRRRR......
...RRRRRRRRR....
...HHHSSSSH.....
..HSHSSSSHSS....
..HSHSSSSSHS....
...SSSSSSSS.....
.N..BBBBBB.N....
NN.BBBBBBBB.NN..
..BBBBRRBBBB....
..BBBRRRRBBB....
..BBBRRRRBBB....
...BBRRRRBB.....
....RRRRRR......
...NN....NN.....
..NN......NN....
.NNN......NNN...
................
................
................
................
................
................
................
................
................
................
................
................
................
`,
  duck: `
................
................
................
................
................
................
................
................
................
................
................
................
....RRRRRR......
...RRRRRRRRR....
...HHHSSSSH.....
..HSHSSSSHSS....
..SSSSSSSSSS....
...BBBBBBBB.....
..BBBRRRRBBB....
..BBRRRRRRBB....
...RRRRRRRR.....
...NNNNNNNN.....
..NNNNNNNNNN....
................
................
................
................
................
................
................
................
`,
};

HERO_B.skid = HERO_B.walk0;
HERO_B.die = HERO_B.jump;

const WALKER = {
  a: `
................
....NNNNNN......
...NNMMMMNN.....
..NMWWWWMWN.....
..NMWKWKMWN.....
..NMMMMMMMWN....
...NMMMMMMN.....
....NNNNNN......
...NN....NN.....
..NNN....NNN....
.NNNN....NNNN...
................
................
................
................
................
`,
  b: `
................
....NNNNNN......
...NNMMMMNN.....
..NMWWWWMWN.....
..NMWKWKMWN.....
..NMMMMMMMWN....
...NMMMMMMN.....
....NNNNNN......
..NN......NN....
.NNN......NNN...
NNNN......NNNN..
................
................
................
................
................
`,
  squish: `
................
................
................
................
................
....NNNNNNNN....
...NMMMMMMMMN...
..NMWKWWKWMWN...
..NMMMMMMMMMN...
...NNNNNNNNN....
................
................
................
................
................
................
`,
};

const TURTLE = {
  a: `
................
......SSSS......
.....SSSSSS.....
.....SKSSKS.....
......SSSS......
...GGGGGGGG.....
..GggGGGggG.....
..GgGGGGGGg.....
..GGGGGGGGG.....
...GggGGggG.....
....NNNNNN......
...NN....NN.....
................
................
................
................
`,
  b: `
................
......SSSS......
.....SSSSSS.....
.....SKSSKS.....
......SSSS......
...GGGGGGGG.....
..GggGGGggG.....
..GgGGGGGGg.....
..GGGGGGGGG.....
...GggGGggG.....
...NN....NN.....
..NNN....NNN....
................
................
................
................
`,
  shell: `
................
................
................
................
...GGGGGGGG.....
..GggGGGggGG....
..GgGGGGGGgG....
..GGGGGGGGGG....
..GggGGGGGGg....
...GGGGGGGG.....
................
................
................
................
................
................
`,
};

const SPINY = {
  a: `
................
...R...R...R....
....R.RRR.R.....
...RRRRRRRRR....
..RRORORORORR...
..RROKOKORORR...
...RRRRRRRRR....
....RRRRRRR.....
.....NNNNN......
....NN...NN.....
................
................
................
................
................
................
`,
  b: `
................
..R..R.R..R.....
...R.RRR.R......
...RRRRRRRRR....
..RRORORORORR...
..RROKOKORORR...
...RRRRRRRRR....
....RRRRRRR.....
....NN...NN.....
...NNN...NNN....
................
................
................
................
................
................
`,
};

const FLYER = {
  a: `
..WW......WW....
.W..W....W..W...
W....WWWW....W..
.W..NNNNNN..W...
..NNMMMMMMNN....
.NMWWWWMWMWN....
.NMWKWKMWMWN....
..NMMMMMMMN.....
...NNNNNNN......
....NN..NN......
................
................
................
................
................
................
`,
  b: `
................
W....WWWW....W..
.W..W....W..W...
..WW.NNNN.WW....
..NNMMMMMMNN....
.NMWWWWMWMWN....
.NMWKWKMWMWN....
..NMMMMMMMN.....
...NNNNNNN......
...NN....NN.....
................
................
................
................
................
................
`,
};

const PIRANHA = {
  a: `
......RR........
.....RRRR.......
....RWWWWR......
...RWKWWKWR.....
...RWWWWWR......
....RRRRRR......
......GG........
......Gg........
......GG........
......gG........
......GG........
......Gg........
......GG........
......gG........
......GG........
......GG........
`
  b: `
.....R....R.....
....RRRRRRR.....
...RWWWWWWWR....
...RWKWWWKWR....
....RWWWWWR.....
.....RRRRR......
......GG........
......gG........
......GG........
......Gg........
......GG........
......gG........
......GG........
......Gg........
......GG........
......GG........
`,
};

const FISH = {
  a: `
................
......TTTTT.....
....TTTTTTTTT...
...TTKTTKTTTT...
..TTTTTTTTTWTT..
...TTTTTTTTT....
....TT.TT.......
......T.........
................
................
................
................
................
................
................
................
`,
  b: `
................
.....TTTTT......
...TTTTTTTTT....
..TTKTTKTTTTT...
.TTTTTTTTTTWTT..
..TTTTTTTTT.....
....TT.TT.......
......T.........
................
................
................
................
................
................
................
................
`,
};

const LAVA_BUBBLE = {
  a: `
................
......RRR.......
....RRRRRRR.....
...RRYYYYRRR....
...RYYYYYYYR....
...RYYKYYKYR....
...RYYYYYYYR....
....RRRRRRR.....
......RRR.......
................
................
................
................
................
................
................
`,
  b: `
................
................
......RRR.......
....RRYYYRR.....
...RYYYYYYYR....
...RYYKYYKYR....
...RYYYYYYYR....
....RRRRRRR.....
.....RRRRR......
................
................
................
................
................
................
................
`,
};

const CANNONBALL = `
................
................
.....dddddd.....
....dDDDDDDd....
...dDDWWDDDDd...
...dDWWDDDDDd...
...dDDDDDDDDd...
...dDDDDDDDDd...
....dDDDDDDd....
.....dddddd.....
................
................
................
................
................
................
`;

const MUSHROOM = `
................
....RRRRRRR.....
...RRWWRRRRR....
..RRWWWWRRRRR...
..RRRRRRRRRRR...
...RRRRRRRRR....
.....SSSSSS.....
.....SKSSKS.....
.....SSSSSS.....
................
................
................
................
................
................
................
`;

const FLOWER = `
................
.....YYYYY......
....YWWWWWY.....
...YWKYKYKWY....
....YWWWWWY.....
.....YYYYY......
......GG........
.....GGGG.......
....G....G......
................
................
................
................
................
................
................
`;

const STAR = `
................
......YY........
......YY........
.....YYYY.......
..YYYYYYYYYY....
...YYYYYYYY.....
....YYYYYY......
...YY....YY.....
..YY......YY....
................
................
................
................
................
................
................
`;

const ONEUP = `
................
....GGGGGGG.....
...GGWWGGGGG....
..GGWWWWGGGGG...
..GGGGGGGGGGG...
...GGGGGGGGG....
.....SSSSSS.....
.....SKSSKS.....
.....SSSSSS.....
................
................
................
................
................
................
................
`;

const COIN = {
  a: `
................
......YYYY......
.....YYYYYY.....
....YYY..YYY....
....YY....YY....
....YY....YY....
....YYY..YYY....
.....YYYYYY.....
......YYYY......
................
................
................
................
................
................
................
`,
  b: `
................
.......YY.......
......YYYY......
......Y..Y......
......Y..Y......
......Y..Y......
......Y..Y......
......YYYY......
.......YY.......
................
................
................
................
................
................
................
`,
};

const FIREBALL = {
  a: `
................
................
......YY........
.....YWWY.......
.....YWWY.......
......YY........
.....RRRR.......
................
................
................
................
................
................
................
................
................
`,
  b: `
................
................
.....YYYY.......
....YWWWWY......
....YWWWWY......
.....YYYY.......
....RRRRRR......
................
................
................
................
................
................
................
................
................
`,
};

const BRICK = `
MMMMMMMMMMMMMMMM
MmmmmmmmmmmmmmNM
MmmWWWWWWWWmmmNM
MmmmmmmmmmmmmmNM
MmmmmmmmmmmmmmNM
NNNNNNNNNNNNNNNN
MmmmmmmmmmmmmmNM
MmmWWWWmmmmmNmNM
MmmmmmmmmmmmmmNM
MmmmmmmmmmmmmmNM
NNNNNNNNNNNNNNNN
MmmmmmmmmmmmmmNM
MmmmmWWWWWWmmmNM
MmmmmmmmmmmmmmNM
MmmmmmmmmmmmmmNM
NNNNNNNNNNNNNNNN
`;

const QBLOCK = `
yyyyyyyyyyyyyyyy
yYYYYYYYYYYYYYoy
yYyyyyyyyyyyYYoy
yYyYYYYYYYYYyYoy
yYyYYyyyyYYyYYoy
yYyYYyYYyyYyYYoy
yYyYYyYYyyYyYYoy
yYyYYyyyyYYyYYoy
yYyYYYYYYYYYyYoy
yYyyyyyyyyyyYYoy
yYyYYYyyyyyyYYoy
yYyYYYYYYYYYyYoy
yYyyyyyyyyyyYYoy
yYYYYYYYYYYYYYoy
yooooooooooooooy
oooooooooooooooo
`;

const USED = `
DDDDDDDDDDDDDDDD
DddddddddddddddD
DddddddddddddddD
DddddddddddddddD
DddddddddddddddD
DddddddddddddddD
DddddddddddddddD
DddddddddddddddD
DddddddddddddddD
DddddddddddddddD
DddddddddddddddD
DddddddddddddddD
DddddddddddddddD
DddddddddddddddD
DddddddddddddddD
DDDDDDDDDDDDDDDD
`;

const HARD = `
dddddddddddddddd
dDDDDDDDDDDDDDDd
dDWWDDDDDDDDDDdd
dDDDDDDDDDDDDDDd
dDDDDDDDDDDDDDDd
dDDDDDDDDDDDDDDd
dDDDDDDDDDDDDDDd
dDDDDDDDDDDDDDDd
dDDDDDDDDDDDDDDd
dDDDDDDDDDDDDDDd
dDDDDDDDDDDDDDDd
dDDDDDDDDDDDDDDd
dDDDDDDDDDDDDDDd
dDDDDDDDDDDDDDDd
dddddddddddddddd
XXXXXXXXXXXXXXXX
`;

const DIRT = `
gggggggggggggggg
gGGGGGGGGGGGGGGg
NNNNNNNNNNNNNNNN
NmMMmMMmMMmMMmNn
NmmMMmmmMMmmMMnn
NmMMmMMmMMmMMmNn
NmmMMmmmMMmmMMnn
NmMMmMMmMMmMMmNn
NmmMMmmmMMmmMMnn
NmMMmMMmMMmMMmNn
NmmMMmmmMMmmMMnn
NmMMmMMmMMmMMmNn
NmmMMmmmMMmmMMnn
NmMMmMMmMMmMMmNn
NNNNNNNNNNNNNNNN
nnnnnnnnnnnnnnnn
`;

const GRASS = `
ZZZZZZZZZZZZZZZZ
ZGGGGGGGGGGGGGGg
GggggggggggggggG
NNNNNNNNNNNNNNNN
NmMMmMMmMMmMMmNn
NmmMMmmmMMmmMMnn
NmMMmMMmMMmMMmNn
NmmMMmmmMMmmMMnn
NmMMmMMmMMmMMmNn
NmmMMmmmMMmmMMnn
NmMMmMMmMMmMMmNn
NmmMMmmmMMmmMMnn
NmMMmMMmMMmMMmNn
NNNNNNNNNNNNNNNN
nnnnnnnnnnnnnnnn
nnnnnnnnnnnnnnnn
`;

const PIPE_L = `
.ggggggggggggggg
gGGGGGGGGGGGGGGg
gGWWWWWWWWWWWWg.
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
.ggggggggggggggg
`;

const PIPE_R = `
ggggggggggggggg.
gGGGGGGGGGGGGGGg
.gWWWWWWWWWWWWGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
ggggggggggggggg.
`;

const PIPE_TOP_L = `
.ggggggggggggggg
gGGGGGGGGGGGGGGg
gGWWWWWWWWWWWWGg
gGGGGGGGGGGGGGGg
gggggggggggggggg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
.ggggggggggggggg
`;

const PIPE_TOP_R = `
ggggggggggggggg.
gGGGGGGGGGGGGGGg
gGWWWWWWWWWWWWGg
gGGGGGGGGGGGGGGg
gggggggggggggggg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
gGGGGGGGGGGGGGGg
ggggggggggggggg.
`;

const CLOUD = `
................
......WWWWW.....
....WWWWWWWWW...
...WWWWWWWWWWW..
.WWWWWWWWWWWWWW.
WWWWWWWWWWWWWWWW
.WWWWWWWWWWWWWW.
................
................
................
................
................
................
................
................
................
`;

const BUSH = `
................
................
......GGGG......
....GGGGGGGG....
...GGGGGGGGGG...
..GGGGGGGGGGGG..
.GGGGGGGGGGGGGG.
GGGGGGGGGGGGGGGG
................
................
................
................
................
................
................
................
`;

const HILL = `
................
.......gg.......
......gGGg......
.....gGGGGg.....
....gGGGGGGg....
...gGGGGGGGGg...
..gGGGGGGGGGGg..
.gGGGGGGGGGGGGg.
gGGGGGGGGGGGGGGg
................
................
................
................
................
................
................
`;

const CASTLE = `
....DDDDDDDD....
...DddddddddD...
..DddDDddDDddD..
..DdDWWDdDWWDd..
..DdDWWDdDWWDd..
..DddDDddDDddD..
.DDDDDDDDDDDDDD.
DddddddddddddddD
DdDDddddddddDDdD
DdWWddddddddWWdD
DdWWddddddddWWdD
DdDDddddddddDDdD
DddddddddddddddD
DdddddXXXXdddddD
DdddddXXXXdddddD
DDDDDDDDDDDDDDDD
`;

const FLAG = `
WW..............
WWYYYYYY........
WWYWWYYYY.......
WWYWYWYYYY......
WWYWWYYYYY......
WWYYYYYYYY......
WW..............
WW..............
WW..............
WW..............
WW..............
WW..............
WW..............
WW..............
WW..............
WW..............
`;

const SPIKE = `
................
.......KK.......
......KWWK......
.....KWWWWK.....
....KWWWWWWK....
...KWWWWWWWWK...
..KWWWWWWWWWWK..
.KKKKKKKKKKKKKK.
................
................
................
................
................
................
................
................
`;

const LAVA = `
LLLLLLLLLLLLLLLL
LRRLRRRLRRRLRRRL
RRRRRRRRRRRRRRRR
rRrRrRrRrRrRrRrR
OOOOOOOOOOOOOOOO
oOoOoOoOoOoOoOoO
yyyyyyyyyyyyyyyy
YYYYYYYYYYYYYYYY
LLLLLLLLLLLLLLLL
LRRLRRRLRRRLRRRL
RRRRRRRRRRRRRRRR
rRrRrRrRrRrRrRrR
OOOOOOOOOOOOOOOO
oOoOoOoOoOoOoOoO
yyyyyyyyyyyyyyyy
YYYYYYYYYYYYYYYY
`;

const WATER = `
TTTTTTTTTTTTTTTT
TAAAAAAAAAAAAAAT
AAAAAAAAAAAAAAAA
TATATATATATATATA
iiiiiiiiiiiiiiii
IIIIIIIIIIIIIIII
iiiiiiiiiiiiiiii
IIIIIIIIIIIIIIII
TTTTTTTTTTTTTTTT
TAAAAAAAAAAAAAAT
AAAAAAAAAAAAAAAA
TATATATATATATATA
iiiiiiiiiiiiiiii
IIIIIIIIIIIIIIII
iiiiiiiiiiiiiiii
IIIIIIIIIIIIIIII
`;

const ICE = `
IIIIIIIIIIIIIIII
IAAAAAAAAAAAAAAI
IAAAAAAAAAAAAAAI
IAAAAAAAAAAAAAAI
IiiiiiiiiiiiiiII
IIIIIIIIIIIIIIII
iiiiiiiiiiiiiiii
IIIIIIIIIIIIIIII
IIIIIIIIIIIIIIII
IAAAAAAAAAAAAAAI
IAAAAAAAAAAAAAAI
IiiiiiiiiiiiiiII
iiiiiiiiiiiiiiii
IIIIIIIIIIIIIIII
iiiiiiiiiiiiiiii
IIIIIIIIIIIIIIII
`;

const NOTE = `
PPPPPPPPPPPPPPPP
PWWWWWWWWWWWWWWP
PWPPPPPPPPPPPPWP
PWPWWWWWWWWWWPWP
PWPWPPPPPPPPWPWP
PWPWPWWWWWWPWPWP
PWPWPWPPPPWPWPWP
PWPWPWPWWPWPWPWP
PWPWPWPPPPWPWPWP
PWPWPWWWWWWPWPWP
PWPWPPPPPPPPWPWP
PWPWWWWWWWWWWPWP
PWPPPPPPPPPPPPWP
PWWWWWWWWWWWWWWP
PPPPPPPPPPPPPPPP
rrrrrrrrrrrrrrrr
`;

const SPRING = `
................
....WWWWWWWW....
...WRRRRRRRRW...
...WRWWWWWWRW...
...WRRRRRRRRW...
....WWWWWWWW....
.....GGGGGG.....
.....GggggG.....
.....GGGGGG.....
.....GggggG.....
.....GGGGGG.....
................
................
................
................
................
`;

const DEBRIS = `
MM..
mMm.
.mM.
..M.
`;

function frames(obj) {
  const out = {};
  for (const [k, v] of Object.entries(obj)) out[k] = paint(v);
  return out;
}

export function buildAtlas() {
  const small = frames(HERO_S);
  const big = frames(HERO_B);
  const fireSmall = {};
  const fireBig = {};
  for (const [k, v] of Object.entries(small)) fireSmall[k] = recolor(v, FIRE_MAP);
  for (const [k, v] of Object.entries(big)) fireBig[k] = recolor(v, FIRE_MAP);

  const walker = frames(WALKER);
  const turtle = frames(TURTLE);
  const redTurtle = {
    a: recolor(turtle.a, {
      [`${hexRgb("#3cb043")}`]: hexRgb("#e52521"),
      [`${hexRgb("#1e7a28")}`]: hexRgb("#9c1410"),
    }),
    b: recolor(turtle.b, {
      [`${hexRgb("#3cb043")}`]: hexRgb("#e52521"),
      [`${hexRgb("#1e7a28")}`]: hexRgb("#9c1410"),
    }),
    shell: recolor(turtle.shell, {
      [`${hexRgb("#3cb043")}`]: hexRgb("#e52521"),
      [`${hexRgb("#1e7a28")}`]: hexRgb("#9c1410"),
    }),
  };

  return {
    small,
    big,
    fireSmall,
    fireBig,
    smallL: Object.fromEntries(Object.entries(small).map(([k, v]) => [k, flipH(v)])),
    bigL: Object.fromEntries(Object.entries(big).map(([k, v]) => [k, flipH(v)])),
    fireSmallL: Object.fromEntries(Object.entries(fireSmall).map(([k, v]) => [k, flipH(v)])),
    fireBigL: Object.fromEntries(Object.entries(fireBig).map(([k, v]) => [k, flipH(v)])),
    walker,
    turtle,
    redTurtle,
    spiny: frames(SPINY),
    flyer: frames(FLYER),
    piranha: frames(PIRANHA),
    fish: frames(FISH),
    lavaBubble: frames(LAVA_BUBBLE),
    cannonball: paint(CANNONBALL),
    mushroom: paint(MUSHROOM),
    flower: paint(FLOWER),
    star: paint(STAR),
    oneup: paint(ONEUP),
    coin: frames(COIN),
    fireball: frames(FIREBALL),
    brick: paint(BRICK),
    qblock: paint(QBLOCK),
    used: paint(USED),
    hard: paint(HARD),
    dirt: paint(DIRT),
    grass: paint(GRASS),
    pipeL: paint(PIPE_L),
    pipeR: paint(PIPE_R),
    pipeTopL: paint(PIPE_TOP_L),
    pipeTopR: paint(PIPE_TOP_R),
    cloud: paint(CLOUD),
    bush: paint(BUSH),
    hill: paint(HILL),
    castle: paint(CASTLE),
    flag: paint(FLAG),
    spike: paint(SPIKE),
    lava: paint(LAVA),
    water: paint(WATER),
    ice: paint(ICE),
    note: paint(NOTE),
    spring: paint(SPRING),
    debris: paint(DEBRIS),
  };
}
