/**
 * Kanto Pokédex #001–151 — official names/types/stats from PokeAPI CSVs
 * (zh-Hans language_id=12). Generated by tools/gen-kanto-dex.mjs — do not edit by hand.
 */

export type DexTypeId =
  | 'bug'
  | 'dragon'
  | 'electric'
  | 'fairy'
  | 'fighting'
  | 'fire'
  | 'flying'
  | 'ghost'
  | 'grass'
  | 'ground'
  | 'ice'
  | 'normal'
  | 'poison'
  | 'psychic'
  | 'rock'
  | 'steel'
  | 'water';

export interface DexEntry {
  /** National dex number 1..151 */
  id: number;
  /** English slug, e.g. "bulbasaur" */
  slug: string;
  /** Simplified Chinese name */
  name: string;
  /** Chinese genus, e.g. "种子宝可梦" */
  genus: string;
  types: DexTypeId[];
  base: { hp: number; atk: number; def: number; spa: number; spd: number; spe: number };
  /** Decimetres */
  height: number;
  /** Hectograms */
  weight: number;
}

export const KANTO_DEX: readonly DexEntry[] = [
  {
    "id": 1,
    "slug": "bulbasaur",
    "name": "妙蛙种子",
    "genus": "种子宝可梦",
    "types": [
      "grass",
      "poison"
    ],
    "base": {
      "hp": 45,
      "atk": 49,
      "def": 49,
      "spa": 65,
      "spd": 65,
      "spe": 45
    },
    "height": 7,
    "weight": 69
  },
  {
    "id": 2,
    "slug": "ivysaur",
    "name": "妙蛙草",
    "genus": "种子宝可梦",
    "types": [
      "grass",
      "poison"
    ],
    "base": {
      "hp": 60,
      "atk": 62,
      "def": 63,
      "spa": 80,
      "spd": 80,
      "spe": 60
    },
    "height": 10,
    "weight": 130
  },
  {
    "id": 3,
    "slug": "venusaur",
    "name": "妙蛙花",
    "genus": "种子宝可梦",
    "types": [
      "grass",
      "poison"
    ],
    "base": {
      "hp": 80,
      "atk": 82,
      "def": 83,
      "spa": 100,
      "spd": 100,
      "spe": 80
    },
    "height": 20,
    "weight": 1000
  },
  {
    "id": 4,
    "slug": "charmander",
    "name": "小火龙",
    "genus": "蜥蜴宝可梦",
    "types": [
      "fire"
    ],
    "base": {
      "hp": 39,
      "atk": 52,
      "def": 43,
      "spa": 60,
      "spd": 50,
      "spe": 65
    },
    "height": 6,
    "weight": 85
  },
  {
    "id": 5,
    "slug": "charmeleon",
    "name": "火恐龙",
    "genus": "火焰宝可梦",
    "types": [
      "fire"
    ],
    "base": {
      "hp": 58,
      "atk": 64,
      "def": 58,
      "spa": 80,
      "spd": 65,
      "spe": 80
    },
    "height": 11,
    "weight": 190
  },
  {
    "id": 6,
    "slug": "charizard",
    "name": "喷火龙",
    "genus": "火焰宝可梦",
    "types": [
      "fire",
      "flying"
    ],
    "base": {
      "hp": 78,
      "atk": 84,
      "def": 78,
      "spa": 109,
      "spd": 85,
      "spe": 100
    },
    "height": 17,
    "weight": 905
  },
  {
    "id": 7,
    "slug": "squirtle",
    "name": "杰尼龟",
    "genus": "小龟宝可梦",
    "types": [
      "water"
    ],
    "base": {
      "hp": 44,
      "atk": 48,
      "def": 65,
      "spa": 50,
      "spd": 64,
      "spe": 43
    },
    "height": 5,
    "weight": 90
  },
  {
    "id": 8,
    "slug": "wartortle",
    "name": "卡咪龟",
    "genus": "龟宝可梦",
    "types": [
      "water"
    ],
    "base": {
      "hp": 59,
      "atk": 63,
      "def": 80,
      "spa": 65,
      "spd": 80,
      "spe": 58
    },
    "height": 10,
    "weight": 225
  },
  {
    "id": 9,
    "slug": "blastoise",
    "name": "水箭龟",
    "genus": "甲壳宝可梦",
    "types": [
      "water"
    ],
    "base": {
      "hp": 79,
      "atk": 83,
      "def": 100,
      "spa": 85,
      "spd": 105,
      "spe": 78
    },
    "height": 16,
    "weight": 855
  },
  {
    "id": 10,
    "slug": "caterpie",
    "name": "绿毛虫",
    "genus": "虫宝宝宝可梦",
    "types": [
      "bug"
    ],
    "base": {
      "hp": 45,
      "atk": 30,
      "def": 35,
      "spa": 20,
      "spd": 20,
      "spe": 45
    },
    "height": 3,
    "weight": 29
  },
  {
    "id": 11,
    "slug": "metapod",
    "name": "铁甲蛹",
    "genus": "蛹宝可梦",
    "types": [
      "bug"
    ],
    "base": {
      "hp": 50,
      "atk": 20,
      "def": 55,
      "spa": 25,
      "spd": 25,
      "spe": 30
    },
    "height": 7,
    "weight": 99
  },
  {
    "id": 12,
    "slug": "butterfree",
    "name": "巴大蝶",
    "genus": "蝴蝶宝可梦",
    "types": [
      "bug",
      "flying"
    ],
    "base": {
      "hp": 60,
      "atk": 45,
      "def": 50,
      "spa": 90,
      "spd": 80,
      "spe": 70
    },
    "height": 11,
    "weight": 320
  },
  {
    "id": 13,
    "slug": "weedle",
    "name": "独角虫",
    "genus": "毛毛虫宝可梦",
    "types": [
      "bug",
      "poison"
    ],
    "base": {
      "hp": 40,
      "atk": 35,
      "def": 30,
      "spa": 20,
      "spd": 20,
      "spe": 50
    },
    "height": 3,
    "weight": 32
  },
  {
    "id": 14,
    "slug": "kakuna",
    "name": "铁壳蛹",
    "genus": "蛹宝可梦",
    "types": [
      "bug",
      "poison"
    ],
    "base": {
      "hp": 45,
      "atk": 25,
      "def": 50,
      "spa": 25,
      "spd": 25,
      "spe": 35
    },
    "height": 6,
    "weight": 100
  },
  {
    "id": 15,
    "slug": "beedrill",
    "name": "大针蜂",
    "genus": "毒蜂宝可梦",
    "types": [
      "bug",
      "poison"
    ],
    "base": {
      "hp": 65,
      "atk": 90,
      "def": 40,
      "spa": 45,
      "spd": 80,
      "spe": 75
    },
    "height": 10,
    "weight": 295
  },
  {
    "id": 16,
    "slug": "pidgey",
    "name": "波波",
    "genus": "小鸟宝可梦",
    "types": [
      "normal",
      "flying"
    ],
    "base": {
      "hp": 40,
      "atk": 45,
      "def": 40,
      "spa": 35,
      "spd": 35,
      "spe": 56
    },
    "height": 3,
    "weight": 18
  },
  {
    "id": 17,
    "slug": "pidgeotto",
    "name": "比比鸟",
    "genus": "鸟宝可梦",
    "types": [
      "normal",
      "flying"
    ],
    "base": {
      "hp": 63,
      "atk": 60,
      "def": 55,
      "spa": 50,
      "spd": 50,
      "spe": 71
    },
    "height": 11,
    "weight": 300
  },
  {
    "id": 18,
    "slug": "pidgeot",
    "name": "大比鸟",
    "genus": "鸟宝可梦",
    "types": [
      "normal",
      "flying"
    ],
    "base": {
      "hp": 83,
      "atk": 80,
      "def": 75,
      "spa": 70,
      "spd": 70,
      "spe": 101
    },
    "height": 15,
    "weight": 395
  },
  {
    "id": 19,
    "slug": "rattata",
    "name": "小拉达",
    "genus": "鼠宝可梦",
    "types": [
      "normal"
    ],
    "base": {
      "hp": 30,
      "atk": 56,
      "def": 35,
      "spa": 25,
      "spd": 35,
      "spe": 72
    },
    "height": 3,
    "weight": 35
  },
  {
    "id": 20,
    "slug": "raticate",
    "name": "拉达",
    "genus": "鼠宝可梦",
    "types": [
      "normal"
    ],
    "base": {
      "hp": 55,
      "atk": 81,
      "def": 60,
      "spa": 50,
      "spd": 70,
      "spe": 97
    },
    "height": 7,
    "weight": 185
  },
  {
    "id": 21,
    "slug": "spearow",
    "name": "烈雀",
    "genus": "小鸟宝可梦",
    "types": [
      "normal",
      "flying"
    ],
    "base": {
      "hp": 40,
      "atk": 60,
      "def": 30,
      "spa": 31,
      "spd": 31,
      "spe": 70
    },
    "height": 3,
    "weight": 20
  },
  {
    "id": 22,
    "slug": "fearow",
    "name": "大嘴雀",
    "genus": "鸟嘴宝可梦",
    "types": [
      "normal",
      "flying"
    ],
    "base": {
      "hp": 65,
      "atk": 90,
      "def": 65,
      "spa": 61,
      "spd": 61,
      "spe": 100
    },
    "height": 12,
    "weight": 380
  },
  {
    "id": 23,
    "slug": "ekans",
    "name": "阿柏蛇",
    "genus": "蛇宝可梦",
    "types": [
      "poison"
    ],
    "base": {
      "hp": 35,
      "atk": 60,
      "def": 44,
      "spa": 40,
      "spd": 54,
      "spe": 55
    },
    "height": 20,
    "weight": 69
  },
  {
    "id": 24,
    "slug": "arbok",
    "name": "阿柏怪",
    "genus": "眼镜蛇宝可梦",
    "types": [
      "poison"
    ],
    "base": {
      "hp": 60,
      "atk": 95,
      "def": 69,
      "spa": 65,
      "spd": 79,
      "spe": 80
    },
    "height": 35,
    "weight": 650
  },
  {
    "id": 25,
    "slug": "pikachu",
    "name": "皮卡丘",
    "genus": "鼠宝可梦",
    "types": [
      "electric"
    ],
    "base": {
      "hp": 35,
      "atk": 55,
      "def": 40,
      "spa": 50,
      "spd": 50,
      "spe": 90
    },
    "height": 4,
    "weight": 60
  },
  {
    "id": 26,
    "slug": "raichu",
    "name": "雷丘",
    "genus": "鼠宝可梦",
    "types": [
      "electric"
    ],
    "base": {
      "hp": 60,
      "atk": 90,
      "def": 55,
      "spa": 90,
      "spd": 80,
      "spe": 110
    },
    "height": 8,
    "weight": 300
  },
  {
    "id": 27,
    "slug": "sandshrew",
    "name": "穿山鼠",
    "genus": "鼠宝可梦",
    "types": [
      "ground"
    ],
    "base": {
      "hp": 50,
      "atk": 75,
      "def": 85,
      "spa": 20,
      "spd": 30,
      "spe": 40
    },
    "height": 6,
    "weight": 120
  },
  {
    "id": 28,
    "slug": "sandslash",
    "name": "穿山王",
    "genus": "鼠宝可梦",
    "types": [
      "ground"
    ],
    "base": {
      "hp": 75,
      "atk": 100,
      "def": 110,
      "spa": 45,
      "spd": 55,
      "spe": 65
    },
    "height": 10,
    "weight": 295
  },
  {
    "id": 29,
    "slug": "nidoran-f",
    "name": "尼多兰",
    "genus": "毒针宝可梦",
    "types": [
      "poison"
    ],
    "base": {
      "hp": 55,
      "atk": 47,
      "def": 52,
      "spa": 40,
      "spd": 40,
      "spe": 41
    },
    "height": 4,
    "weight": 70
  },
  {
    "id": 30,
    "slug": "nidorina",
    "name": "尼多娜",
    "genus": "毒针宝可梦",
    "types": [
      "poison"
    ],
    "base": {
      "hp": 70,
      "atk": 62,
      "def": 67,
      "spa": 55,
      "spd": 55,
      "spe": 56
    },
    "height": 8,
    "weight": 200
  },
  {
    "id": 31,
    "slug": "nidoqueen",
    "name": "尼多后",
    "genus": "钻锥宝可梦",
    "types": [
      "poison",
      "ground"
    ],
    "base": {
      "hp": 90,
      "atk": 92,
      "def": 87,
      "spa": 75,
      "spd": 85,
      "spe": 76
    },
    "height": 13,
    "weight": 600
  },
  {
    "id": 32,
    "slug": "nidoran-m",
    "name": "尼多朗",
    "genus": "毒针宝可梦",
    "types": [
      "poison"
    ],
    "base": {
      "hp": 46,
      "atk": 57,
      "def": 40,
      "spa": 40,
      "spd": 40,
      "spe": 50
    },
    "height": 5,
    "weight": 90
  },
  {
    "id": 33,
    "slug": "nidorino",
    "name": "尼多力诺",
    "genus": "毒针宝可梦",
    "types": [
      "poison"
    ],
    "base": {
      "hp": 61,
      "atk": 72,
      "def": 57,
      "spa": 55,
      "spd": 55,
      "spe": 65
    },
    "height": 9,
    "weight": 195
  },
  {
    "id": 34,
    "slug": "nidoking",
    "name": "尼多王",
    "genus": "钻锥宝可梦",
    "types": [
      "poison",
      "ground"
    ],
    "base": {
      "hp": 81,
      "atk": 102,
      "def": 77,
      "spa": 85,
      "spd": 75,
      "spe": 85
    },
    "height": 14,
    "weight": 620
  },
  {
    "id": 35,
    "slug": "clefairy",
    "name": "皮皮",
    "genus": "妖精宝可梦",
    "types": [
      "fairy"
    ],
    "base": {
      "hp": 70,
      "atk": 45,
      "def": 48,
      "spa": 60,
      "spd": 65,
      "spe": 35
    },
    "height": 6,
    "weight": 75
  },
  {
    "id": 36,
    "slug": "clefable",
    "name": "皮可西",
    "genus": "妖精宝可梦",
    "types": [
      "fairy"
    ],
    "base": {
      "hp": 95,
      "atk": 70,
      "def": 73,
      "spa": 95,
      "spd": 90,
      "spe": 60
    },
    "height": 13,
    "weight": 400
  },
  {
    "id": 37,
    "slug": "vulpix",
    "name": "六尾",
    "genus": "狐狸宝可梦",
    "types": [
      "fire"
    ],
    "base": {
      "hp": 38,
      "atk": 41,
      "def": 40,
      "spa": 50,
      "spd": 65,
      "spe": 65
    },
    "height": 6,
    "weight": 99
  },
  {
    "id": 38,
    "slug": "ninetales",
    "name": "九尾",
    "genus": "狐狸宝可梦",
    "types": [
      "fire"
    ],
    "base": {
      "hp": 73,
      "atk": 76,
      "def": 75,
      "spa": 81,
      "spd": 100,
      "spe": 100
    },
    "height": 11,
    "weight": 199
  },
  {
    "id": 39,
    "slug": "jigglypuff",
    "name": "胖丁",
    "genus": "气球宝可梦",
    "types": [
      "normal",
      "fairy"
    ],
    "base": {
      "hp": 115,
      "atk": 45,
      "def": 20,
      "spa": 45,
      "spd": 25,
      "spe": 20
    },
    "height": 5,
    "weight": 55
  },
  {
    "id": 40,
    "slug": "wigglytuff",
    "name": "胖可丁",
    "genus": "气球宝可梦",
    "types": [
      "normal",
      "fairy"
    ],
    "base": {
      "hp": 140,
      "atk": 70,
      "def": 45,
      "spa": 85,
      "spd": 50,
      "spe": 45
    },
    "height": 10,
    "weight": 120
  },
  {
    "id": 41,
    "slug": "zubat",
    "name": "超音蝠",
    "genus": "蝙蝠宝可梦",
    "types": [
      "poison",
      "flying"
    ],
    "base": {
      "hp": 40,
      "atk": 45,
      "def": 35,
      "spa": 30,
      "spd": 40,
      "spe": 55
    },
    "height": 8,
    "weight": 75
  },
  {
    "id": 42,
    "slug": "golbat",
    "name": "大嘴蝠",
    "genus": "蝙蝠宝可梦",
    "types": [
      "poison",
      "flying"
    ],
    "base": {
      "hp": 75,
      "atk": 80,
      "def": 70,
      "spa": 65,
      "spd": 75,
      "spe": 90
    },
    "height": 16,
    "weight": 550
  },
  {
    "id": 43,
    "slug": "oddish",
    "name": "走路草",
    "genus": "杂草宝可梦",
    "types": [
      "grass",
      "poison"
    ],
    "base": {
      "hp": 45,
      "atk": 50,
      "def": 55,
      "spa": 75,
      "spd": 65,
      "spe": 30
    },
    "height": 5,
    "weight": 54
  },
  {
    "id": 44,
    "slug": "gloom",
    "name": "臭臭花",
    "genus": "杂草宝可梦",
    "types": [
      "grass",
      "poison"
    ],
    "base": {
      "hp": 60,
      "atk": 65,
      "def": 70,
      "spa": 85,
      "spd": 75,
      "spe": 40
    },
    "height": 8,
    "weight": 86
  },
  {
    "id": 45,
    "slug": "vileplume",
    "name": "霸王花",
    "genus": "花宝可梦",
    "types": [
      "grass",
      "poison"
    ],
    "base": {
      "hp": 75,
      "atk": 80,
      "def": 85,
      "spa": 110,
      "spd": 90,
      "spe": 50
    },
    "height": 12,
    "weight": 186
  },
  {
    "id": 46,
    "slug": "paras",
    "name": "派拉斯",
    "genus": "蘑菇宝可梦",
    "types": [
      "bug",
      "grass"
    ],
    "base": {
      "hp": 35,
      "atk": 70,
      "def": 55,
      "spa": 45,
      "spd": 55,
      "spe": 25
    },
    "height": 3,
    "weight": 54
  },
  {
    "id": 47,
    "slug": "parasect",
    "name": "派拉斯特",
    "genus": "蘑菇宝可梦",
    "types": [
      "bug",
      "grass"
    ],
    "base": {
      "hp": 60,
      "atk": 95,
      "def": 80,
      "spa": 60,
      "spd": 80,
      "spe": 30
    },
    "height": 10,
    "weight": 295
  },
  {
    "id": 48,
    "slug": "venonat",
    "name": "毛球",
    "genus": "昆虫宝可梦",
    "types": [
      "bug",
      "poison"
    ],
    "base": {
      "hp": 60,
      "atk": 55,
      "def": 50,
      "spa": 40,
      "spd": 55,
      "spe": 45
    },
    "height": 10,
    "weight": 300
  },
  {
    "id": 49,
    "slug": "venomoth",
    "name": "摩鲁蛾",
    "genus": "毒蛾宝可梦",
    "types": [
      "bug",
      "poison"
    ],
    "base": {
      "hp": 70,
      "atk": 65,
      "def": 60,
      "spa": 90,
      "spd": 75,
      "spe": 90
    },
    "height": 15,
    "weight": 125
  },
  {
    "id": 50,
    "slug": "diglett",
    "name": "地鼠",
    "genus": "鼹鼠宝可梦",
    "types": [
      "ground"
    ],
    "base": {
      "hp": 10,
      "atk": 55,
      "def": 25,
      "spa": 35,
      "spd": 45,
      "spe": 95
    },
    "height": 2,
    "weight": 8
  },
  {
    "id": 51,
    "slug": "dugtrio",
    "name": "三地鼠",
    "genus": "鼹鼠宝可梦",
    "types": [
      "ground"
    ],
    "base": {
      "hp": 35,
      "atk": 100,
      "def": 50,
      "spa": 50,
      "spd": 70,
      "spe": 120
    },
    "height": 7,
    "weight": 333
  },
  {
    "id": 52,
    "slug": "meowth",
    "name": "喵喵",
    "genus": "妖怪猫宝可梦",
    "types": [
      "normal"
    ],
    "base": {
      "hp": 40,
      "atk": 45,
      "def": 35,
      "spa": 40,
      "spd": 40,
      "spe": 90
    },
    "height": 4,
    "weight": 42
  },
  {
    "id": 53,
    "slug": "persian",
    "name": "猫老大",
    "genus": "暹罗猫宝可梦",
    "types": [
      "normal"
    ],
    "base": {
      "hp": 65,
      "atk": 70,
      "def": 60,
      "spa": 65,
      "spd": 65,
      "spe": 115
    },
    "height": 10,
    "weight": 320
  },
  {
    "id": 54,
    "slug": "psyduck",
    "name": "可达鸭",
    "genus": "鸭宝可梦",
    "types": [
      "water"
    ],
    "base": {
      "hp": 50,
      "atk": 52,
      "def": 48,
      "spa": 65,
      "spd": 50,
      "spe": 55
    },
    "height": 8,
    "weight": 196
  },
  {
    "id": 55,
    "slug": "golduck",
    "name": "哥达鸭",
    "genus": "鸭宝可梦",
    "types": [
      "water"
    ],
    "base": {
      "hp": 80,
      "atk": 82,
      "def": 78,
      "spa": 95,
      "spd": 80,
      "spe": 85
    },
    "height": 17,
    "weight": 766
  },
  {
    "id": 56,
    "slug": "mankey",
    "name": "猴怪",
    "genus": "猪猴宝可梦",
    "types": [
      "fighting"
    ],
    "base": {
      "hp": 40,
      "atk": 80,
      "def": 35,
      "spa": 35,
      "spd": 45,
      "spe": 70
    },
    "height": 5,
    "weight": 280
  },
  {
    "id": 57,
    "slug": "primeape",
    "name": "火暴猴",
    "genus": "猪猴宝可梦",
    "types": [
      "fighting"
    ],
    "base": {
      "hp": 65,
      "atk": 105,
      "def": 60,
      "spa": 60,
      "spd": 70,
      "spe": 95
    },
    "height": 10,
    "weight": 320
  },
  {
    "id": 58,
    "slug": "growlithe",
    "name": "卡蒂狗",
    "genus": "小狗宝可梦",
    "types": [
      "fire"
    ],
    "base": {
      "hp": 55,
      "atk": 70,
      "def": 45,
      "spa": 70,
      "spd": 50,
      "spe": 60
    },
    "height": 7,
    "weight": 190
  },
  {
    "id": 59,
    "slug": "arcanine",
    "name": "风速狗",
    "genus": "传说宝可梦",
    "types": [
      "fire"
    ],
    "base": {
      "hp": 90,
      "atk": 110,
      "def": 80,
      "spa": 100,
      "spd": 80,
      "spe": 95
    },
    "height": 19,
    "weight": 1550
  },
  {
    "id": 60,
    "slug": "poliwag",
    "name": "蚊香蝌蚪",
    "genus": "蝌蚪宝可梦",
    "types": [
      "water"
    ],
    "base": {
      "hp": 40,
      "atk": 50,
      "def": 40,
      "spa": 40,
      "spd": 40,
      "spe": 90
    },
    "height": 6,
    "weight": 124
  },
  {
    "id": 61,
    "slug": "poliwhirl",
    "name": "蚊香君",
    "genus": "蝌蚪宝可梦",
    "types": [
      "water"
    ],
    "base": {
      "hp": 65,
      "atk": 65,
      "def": 65,
      "spa": 50,
      "spd": 50,
      "spe": 90
    },
    "height": 10,
    "weight": 200
  },
  {
    "id": 62,
    "slug": "poliwrath",
    "name": "蚊香泳士",
    "genus": "蝌蚪宝可梦",
    "types": [
      "water",
      "fighting"
    ],
    "base": {
      "hp": 90,
      "atk": 95,
      "def": 95,
      "spa": 70,
      "spd": 90,
      "spe": 70
    },
    "height": 13,
    "weight": 540
  },
  {
    "id": 63,
    "slug": "abra",
    "name": "凯西",
    "genus": "念力宝可梦",
    "types": [
      "psychic"
    ],
    "base": {
      "hp": 25,
      "atk": 20,
      "def": 15,
      "spa": 105,
      "spd": 55,
      "spe": 90
    },
    "height": 9,
    "weight": 195
  },
  {
    "id": 64,
    "slug": "kadabra",
    "name": "勇基拉",
    "genus": "念力宝可梦",
    "types": [
      "psychic"
    ],
    "base": {
      "hp": 40,
      "atk": 35,
      "def": 30,
      "spa": 120,
      "spd": 70,
      "spe": 105
    },
    "height": 13,
    "weight": 565
  },
  {
    "id": 65,
    "slug": "alakazam",
    "name": "胡地",
    "genus": "念力宝可梦",
    "types": [
      "psychic"
    ],
    "base": {
      "hp": 55,
      "atk": 50,
      "def": 45,
      "spa": 135,
      "spd": 95,
      "spe": 120
    },
    "height": 15,
    "weight": 480
  },
  {
    "id": 66,
    "slug": "machop",
    "name": "腕力",
    "genus": "怪力宝可梦",
    "types": [
      "fighting"
    ],
    "base": {
      "hp": 70,
      "atk": 80,
      "def": 50,
      "spa": 35,
      "spd": 35,
      "spe": 35
    },
    "height": 8,
    "weight": 195
  },
  {
    "id": 67,
    "slug": "machoke",
    "name": "豪力",
    "genus": "怪力宝可梦",
    "types": [
      "fighting"
    ],
    "base": {
      "hp": 80,
      "atk": 100,
      "def": 70,
      "spa": 50,
      "spd": 60,
      "spe": 45
    },
    "height": 15,
    "weight": 705
  },
  {
    "id": 68,
    "slug": "machamp",
    "name": "怪力",
    "genus": "怪力宝可梦",
    "types": [
      "fighting"
    ],
    "base": {
      "hp": 90,
      "atk": 130,
      "def": 80,
      "spa": 65,
      "spd": 85,
      "spe": 55
    },
    "height": 16,
    "weight": 1300
  },
  {
    "id": 69,
    "slug": "bellsprout",
    "name": "喇叭芽",
    "genus": "花宝可梦",
    "types": [
      "grass",
      "poison"
    ],
    "base": {
      "hp": 50,
      "atk": 75,
      "def": 35,
      "spa": 70,
      "spd": 30,
      "spe": 40
    },
    "height": 7,
    "weight": 40
  },
  {
    "id": 70,
    "slug": "weepinbell",
    "name": "口呆花",
    "genus": "捕蝇宝可梦",
    "types": [
      "grass",
      "poison"
    ],
    "base": {
      "hp": 65,
      "atk": 90,
      "def": 50,
      "spa": 85,
      "spd": 45,
      "spe": 55
    },
    "height": 10,
    "weight": 64
  },
  {
    "id": 71,
    "slug": "victreebel",
    "name": "大食花",
    "genus": "捕蝇宝可梦",
    "types": [
      "grass",
      "poison"
    ],
    "base": {
      "hp": 80,
      "atk": 105,
      "def": 65,
      "spa": 100,
      "spd": 70,
      "spe": 70
    },
    "height": 17,
    "weight": 155
  },
  {
    "id": 72,
    "slug": "tentacool",
    "name": "玛瑙水母",
    "genus": "水母宝可梦",
    "types": [
      "water",
      "poison"
    ],
    "base": {
      "hp": 40,
      "atk": 40,
      "def": 35,
      "spa": 50,
      "spd": 100,
      "spe": 70
    },
    "height": 9,
    "weight": 455
  },
  {
    "id": 73,
    "slug": "tentacruel",
    "name": "毒刺水母",
    "genus": "水母宝可梦",
    "types": [
      "water",
      "poison"
    ],
    "base": {
      "hp": 80,
      "atk": 70,
      "def": 65,
      "spa": 80,
      "spd": 120,
      "spe": 100
    },
    "height": 16,
    "weight": 550
  },
  {
    "id": 74,
    "slug": "geodude",
    "name": "小拳石",
    "genus": "岩石宝可梦",
    "types": [
      "rock",
      "ground"
    ],
    "base": {
      "hp": 40,
      "atk": 80,
      "def": 100,
      "spa": 30,
      "spd": 30,
      "spe": 20
    },
    "height": 4,
    "weight": 200
  },
  {
    "id": 75,
    "slug": "graveler",
    "name": "隆隆石",
    "genus": "岩石宝可梦",
    "types": [
      "rock",
      "ground"
    ],
    "base": {
      "hp": 55,
      "atk": 95,
      "def": 115,
      "spa": 45,
      "spd": 45,
      "spe": 35
    },
    "height": 10,
    "weight": 1050
  },
  {
    "id": 76,
    "slug": "golem",
    "name": "隆隆岩",
    "genus": "重量级宝可梦",
    "types": [
      "rock",
      "ground"
    ],
    "base": {
      "hp": 80,
      "atk": 120,
      "def": 130,
      "spa": 55,
      "spd": 65,
      "spe": 45
    },
    "height": 14,
    "weight": 3000
  },
  {
    "id": 77,
    "slug": "ponyta",
    "name": "小火马",
    "genus": "火马宝可梦",
    "types": [
      "fire"
    ],
    "base": {
      "hp": 50,
      "atk": 85,
      "def": 55,
      "spa": 65,
      "spd": 65,
      "spe": 90
    },
    "height": 10,
    "weight": 300
  },
  {
    "id": 78,
    "slug": "rapidash",
    "name": "烈焰马",
    "genus": "火马宝可梦",
    "types": [
      "fire"
    ],
    "base": {
      "hp": 65,
      "atk": 100,
      "def": 70,
      "spa": 80,
      "spd": 80,
      "spe": 105
    },
    "height": 17,
    "weight": 950
  },
  {
    "id": 79,
    "slug": "slowpoke",
    "name": "呆呆兽",
    "genus": "憨憨宝可梦",
    "types": [
      "water",
      "psychic"
    ],
    "base": {
      "hp": 90,
      "atk": 65,
      "def": 65,
      "spa": 40,
      "spd": 40,
      "spe": 15
    },
    "height": 12,
    "weight": 360
  },
  {
    "id": 80,
    "slug": "slowbro",
    "name": "呆壳兽",
    "genus": "寄居蟹宝可梦",
    "types": [
      "water",
      "psychic"
    ],
    "base": {
      "hp": 95,
      "atk": 75,
      "def": 110,
      "spa": 100,
      "spd": 80,
      "spe": 30
    },
    "height": 16,
    "weight": 785
  },
  {
    "id": 81,
    "slug": "magnemite",
    "name": "小磁怪",
    "genus": "磁铁宝可梦",
    "types": [
      "electric",
      "steel"
    ],
    "base": {
      "hp": 25,
      "atk": 35,
      "def": 70,
      "spa": 95,
      "spd": 55,
      "spe": 45
    },
    "height": 3,
    "weight": 60
  },
  {
    "id": 82,
    "slug": "magneton",
    "name": "三合一磁怪",
    "genus": "磁铁宝可梦",
    "types": [
      "electric",
      "steel"
    ],
    "base": {
      "hp": 50,
      "atk": 60,
      "def": 95,
      "spa": 120,
      "spd": 70,
      "spe": 70
    },
    "height": 10,
    "weight": 600
  },
  {
    "id": 83,
    "slug": "farfetchd",
    "name": "大葱鸭",
    "genus": "黄嘴鸭宝可梦",
    "types": [
      "normal",
      "flying"
    ],
    "base": {
      "hp": 52,
      "atk": 90,
      "def": 55,
      "spa": 58,
      "spd": 62,
      "spe": 60
    },
    "height": 8,
    "weight": 150
  },
  {
    "id": 84,
    "slug": "doduo",
    "name": "嘟嘟",
    "genus": "两头鸟宝可梦",
    "types": [
      "normal",
      "flying"
    ],
    "base": {
      "hp": 35,
      "atk": 85,
      "def": 45,
      "spa": 35,
      "spd": 35,
      "spe": 75
    },
    "height": 14,
    "weight": 392
  },
  {
    "id": 85,
    "slug": "dodrio",
    "name": "嘟嘟利",
    "genus": "三头鸟宝可梦",
    "types": [
      "normal",
      "flying"
    ],
    "base": {
      "hp": 60,
      "atk": 110,
      "def": 70,
      "spa": 60,
      "spd": 60,
      "spe": 110
    },
    "height": 18,
    "weight": 852
  },
  {
    "id": 86,
    "slug": "seel",
    "name": "小海狮",
    "genus": "海狮宝可梦",
    "types": [
      "water"
    ],
    "base": {
      "hp": 65,
      "atk": 45,
      "def": 55,
      "spa": 45,
      "spd": 70,
      "spe": 45
    },
    "height": 11,
    "weight": 900
  },
  {
    "id": 87,
    "slug": "dewgong",
    "name": "白海狮",
    "genus": "海狮宝可梦",
    "types": [
      "water",
      "ice"
    ],
    "base": {
      "hp": 90,
      "atk": 70,
      "def": 80,
      "spa": 70,
      "spd": 95,
      "spe": 70
    },
    "height": 17,
    "weight": 1200
  },
  {
    "id": 88,
    "slug": "grimer",
    "name": "臭泥",
    "genus": "污泥宝可梦",
    "types": [
      "poison"
    ],
    "base": {
      "hp": 80,
      "atk": 80,
      "def": 50,
      "spa": 40,
      "spd": 50,
      "spe": 25
    },
    "height": 9,
    "weight": 300
  },
  {
    "id": 89,
    "slug": "muk",
    "name": "臭臭泥",
    "genus": "污泥宝可梦",
    "types": [
      "poison"
    ],
    "base": {
      "hp": 105,
      "atk": 105,
      "def": 75,
      "spa": 65,
      "spd": 100,
      "spe": 50
    },
    "height": 12,
    "weight": 300
  },
  {
    "id": 90,
    "slug": "shellder",
    "name": "大舌贝",
    "genus": "双壳贝宝可梦",
    "types": [
      "water"
    ],
    "base": {
      "hp": 30,
      "atk": 65,
      "def": 100,
      "spa": 45,
      "spd": 25,
      "spe": 40
    },
    "height": 3,
    "weight": 40
  },
  {
    "id": 91,
    "slug": "cloyster",
    "name": "刺甲贝",
    "genus": "双壳贝宝可梦",
    "types": [
      "water",
      "ice"
    ],
    "base": {
      "hp": 50,
      "atk": 95,
      "def": 180,
      "spa": 85,
      "spd": 45,
      "spe": 70
    },
    "height": 15,
    "weight": 1325
  },
  {
    "id": 92,
    "slug": "gastly",
    "name": "鬼斯",
    "genus": "气体状宝可梦",
    "types": [
      "ghost",
      "poison"
    ],
    "base": {
      "hp": 30,
      "atk": 35,
      "def": 30,
      "spa": 100,
      "spd": 35,
      "spe": 80
    },
    "height": 13,
    "weight": 1
  },
  {
    "id": 93,
    "slug": "haunter",
    "name": "鬼斯通",
    "genus": "气体状宝可梦",
    "types": [
      "ghost",
      "poison"
    ],
    "base": {
      "hp": 45,
      "atk": 50,
      "def": 45,
      "spa": 115,
      "spd": 55,
      "spe": 95
    },
    "height": 16,
    "weight": 1
  },
  {
    "id": 94,
    "slug": "gengar",
    "name": "耿鬼",
    "genus": "影子宝可梦",
    "types": [
      "ghost",
      "poison"
    ],
    "base": {
      "hp": 60,
      "atk": 65,
      "def": 60,
      "spa": 130,
      "spd": 75,
      "spe": 110
    },
    "height": 15,
    "weight": 405
  },
  {
    "id": 95,
    "slug": "onix",
    "name": "大岩蛇",
    "genus": "岩蛇宝可梦",
    "types": [
      "rock",
      "ground"
    ],
    "base": {
      "hp": 35,
      "atk": 45,
      "def": 160,
      "spa": 30,
      "spd": 45,
      "spe": 70
    },
    "height": 88,
    "weight": 2100
  },
  {
    "id": 96,
    "slug": "drowzee",
    "name": "催眠貘",
    "genus": "催眠宝可梦",
    "types": [
      "psychic"
    ],
    "base": {
      "hp": 60,
      "atk": 48,
      "def": 45,
      "spa": 43,
      "spd": 90,
      "spe": 42
    },
    "height": 10,
    "weight": 324
  },
  {
    "id": 97,
    "slug": "hypno",
    "name": "引梦貘人",
    "genus": "催眠宝可梦",
    "types": [
      "psychic"
    ],
    "base": {
      "hp": 85,
      "atk": 73,
      "def": 70,
      "spa": 73,
      "spd": 115,
      "spe": 67
    },
    "height": 16,
    "weight": 756
  },
  {
    "id": 98,
    "slug": "krabby",
    "name": "大钳蟹",
    "genus": "清水蟹宝可梦",
    "types": [
      "water"
    ],
    "base": {
      "hp": 30,
      "atk": 105,
      "def": 90,
      "spa": 25,
      "spd": 25,
      "spe": 50
    },
    "height": 4,
    "weight": 65
  },
  {
    "id": 99,
    "slug": "kingler",
    "name": "巨钳蟹",
    "genus": "钳子宝可梦",
    "types": [
      "water"
    ],
    "base": {
      "hp": 55,
      "atk": 130,
      "def": 115,
      "spa": 50,
      "spd": 50,
      "spe": 75
    },
    "height": 13,
    "weight": 600
  },
  {
    "id": 100,
    "slug": "voltorb",
    "name": "霹雳电球",
    "genus": "球宝可梦",
    "types": [
      "electric"
    ],
    "base": {
      "hp": 40,
      "atk": 30,
      "def": 50,
      "spa": 55,
      "spd": 55,
      "spe": 100
    },
    "height": 5,
    "weight": 104
  },
  {
    "id": 101,
    "slug": "electrode",
    "name": "顽皮雷弹",
    "genus": "球宝可梦",
    "types": [
      "electric"
    ],
    "base": {
      "hp": 60,
      "atk": 50,
      "def": 70,
      "spa": 80,
      "spd": 80,
      "spe": 150
    },
    "height": 12,
    "weight": 666
  },
  {
    "id": 102,
    "slug": "exeggcute",
    "name": "蛋蛋",
    "genus": "蛋宝可梦",
    "types": [
      "grass",
      "psychic"
    ],
    "base": {
      "hp": 60,
      "atk": 40,
      "def": 80,
      "spa": 60,
      "spd": 45,
      "spe": 40
    },
    "height": 4,
    "weight": 25
  },
  {
    "id": 103,
    "slug": "exeggutor",
    "name": "椰蛋树",
    "genus": "椰子宝可梦",
    "types": [
      "grass",
      "psychic"
    ],
    "base": {
      "hp": 95,
      "atk": 95,
      "def": 85,
      "spa": 125,
      "spd": 75,
      "spe": 55
    },
    "height": 20,
    "weight": 1200
  },
  {
    "id": 104,
    "slug": "cubone",
    "name": "卡拉卡拉",
    "genus": "孤独宝可梦",
    "types": [
      "ground"
    ],
    "base": {
      "hp": 50,
      "atk": 50,
      "def": 95,
      "spa": 40,
      "spd": 50,
      "spe": 35
    },
    "height": 4,
    "weight": 65
  },
  {
    "id": 105,
    "slug": "marowak",
    "name": "嘎啦嘎啦",
    "genus": "爱骨宝可梦",
    "types": [
      "ground"
    ],
    "base": {
      "hp": 60,
      "atk": 80,
      "def": 110,
      "spa": 50,
      "spd": 80,
      "spe": 45
    },
    "height": 10,
    "weight": 450
  },
  {
    "id": 106,
    "slug": "hitmonlee",
    "name": "飞腿郎",
    "genus": "踢腿宝可梦",
    "types": [
      "fighting"
    ],
    "base": {
      "hp": 50,
      "atk": 120,
      "def": 53,
      "spa": 35,
      "spd": 110,
      "spe": 87
    },
    "height": 15,
    "weight": 498
  },
  {
    "id": 107,
    "slug": "hitmonchan",
    "name": "快拳郎",
    "genus": "拳击宝可梦",
    "types": [
      "fighting"
    ],
    "base": {
      "hp": 50,
      "atk": 105,
      "def": 79,
      "spa": 35,
      "spd": 110,
      "spe": 76
    },
    "height": 14,
    "weight": 502
  },
  {
    "id": 108,
    "slug": "lickitung",
    "name": "大舌头",
    "genus": "舔舔宝可梦",
    "types": [
      "normal"
    ],
    "base": {
      "hp": 90,
      "atk": 55,
      "def": 75,
      "spa": 60,
      "spd": 75,
      "spe": 30
    },
    "height": 12,
    "weight": 655
  },
  {
    "id": 109,
    "slug": "koffing",
    "name": "瓦斯弹",
    "genus": "毒气宝可梦",
    "types": [
      "poison"
    ],
    "base": {
      "hp": 40,
      "atk": 65,
      "def": 95,
      "spa": 60,
      "spd": 45,
      "spe": 35
    },
    "height": 6,
    "weight": 10
  },
  {
    "id": 110,
    "slug": "weezing",
    "name": "双弹瓦斯",
    "genus": "毒气宝可梦",
    "types": [
      "poison"
    ],
    "base": {
      "hp": 65,
      "atk": 90,
      "def": 120,
      "spa": 85,
      "spd": 70,
      "spe": 60
    },
    "height": 12,
    "weight": 95
  },
  {
    "id": 111,
    "slug": "rhyhorn",
    "name": "独角犀牛",
    "genus": "尖尖宝可梦",
    "types": [
      "ground",
      "rock"
    ],
    "base": {
      "hp": 80,
      "atk": 85,
      "def": 95,
      "spa": 30,
      "spd": 30,
      "spe": 25
    },
    "height": 10,
    "weight": 1150
  },
  {
    "id": 112,
    "slug": "rhydon",
    "name": "钻角犀兽",
    "genus": "钻锥宝可梦",
    "types": [
      "ground",
      "rock"
    ],
    "base": {
      "hp": 105,
      "atk": 130,
      "def": 120,
      "spa": 45,
      "spd": 45,
      "spe": 40
    },
    "height": 19,
    "weight": 1200
  },
  {
    "id": 113,
    "slug": "chansey",
    "name": "吉利蛋",
    "genus": "蛋宝可梦",
    "types": [
      "normal"
    ],
    "base": {
      "hp": 250,
      "atk": 5,
      "def": 5,
      "spa": 35,
      "spd": 105,
      "spe": 50
    },
    "height": 11,
    "weight": 346
  },
  {
    "id": 114,
    "slug": "tangela",
    "name": "蔓藤怪",
    "genus": "藤蔓状宝可梦",
    "types": [
      "grass"
    ],
    "base": {
      "hp": 65,
      "atk": 55,
      "def": 115,
      "spa": 100,
      "spd": 40,
      "spe": 60
    },
    "height": 10,
    "weight": 350
  },
  {
    "id": 115,
    "slug": "kangaskhan",
    "name": "袋兽",
    "genus": "亲子宝可梦",
    "types": [
      "normal"
    ],
    "base": {
      "hp": 105,
      "atk": 95,
      "def": 80,
      "spa": 40,
      "spd": 80,
      "spe": 90
    },
    "height": 22,
    "weight": 800
  },
  {
    "id": 116,
    "slug": "horsea",
    "name": "墨海马",
    "genus": "龙宝可梦",
    "types": [
      "water"
    ],
    "base": {
      "hp": 30,
      "atk": 40,
      "def": 70,
      "spa": 70,
      "spd": 25,
      "spe": 60
    },
    "height": 4,
    "weight": 80
  },
  {
    "id": 117,
    "slug": "seadra",
    "name": "海刺龙",
    "genus": "龙宝可梦",
    "types": [
      "water"
    ],
    "base": {
      "hp": 55,
      "atk": 65,
      "def": 95,
      "spa": 95,
      "spd": 45,
      "spe": 85
    },
    "height": 12,
    "weight": 250
  },
  {
    "id": 118,
    "slug": "goldeen",
    "name": "角金鱼",
    "genus": "金鱼宝可梦",
    "types": [
      "water"
    ],
    "base": {
      "hp": 45,
      "atk": 67,
      "def": 60,
      "spa": 35,
      "spd": 50,
      "spe": 63
    },
    "height": 6,
    "weight": 150
  },
  {
    "id": 119,
    "slug": "seaking",
    "name": "金鱼王",
    "genus": "金鱼宝可梦",
    "types": [
      "water"
    ],
    "base": {
      "hp": 80,
      "atk": 92,
      "def": 65,
      "spa": 65,
      "spd": 80,
      "spe": 68
    },
    "height": 13,
    "weight": 390
  },
  {
    "id": 120,
    "slug": "staryu",
    "name": "海星星",
    "genus": "星形宝可梦",
    "types": [
      "water"
    ],
    "base": {
      "hp": 30,
      "atk": 45,
      "def": 55,
      "spa": 70,
      "spd": 55,
      "spe": 85
    },
    "height": 8,
    "weight": 345
  },
  {
    "id": 121,
    "slug": "starmie",
    "name": "宝石海星",
    "genus": "谜宝可梦",
    "types": [
      "water",
      "psychic"
    ],
    "base": {
      "hp": 60,
      "atk": 75,
      "def": 85,
      "spa": 100,
      "spd": 85,
      "spe": 115
    },
    "height": 11,
    "weight": 800
  },
  {
    "id": 122,
    "slug": "mr-mime",
    "name": "魔墙人偶",
    "genus": "屏障宝可梦",
    "types": [
      "psychic",
      "fairy"
    ],
    "base": {
      "hp": 40,
      "atk": 45,
      "def": 65,
      "spa": 100,
      "spd": 120,
      "spe": 90
    },
    "height": 13,
    "weight": 545
  },
  {
    "id": 123,
    "slug": "scyther",
    "name": "飞天螳螂",
    "genus": "螳螂宝可梦",
    "types": [
      "bug",
      "flying"
    ],
    "base": {
      "hp": 70,
      "atk": 110,
      "def": 80,
      "spa": 55,
      "spd": 80,
      "spe": 105
    },
    "height": 15,
    "weight": 560
  },
  {
    "id": 124,
    "slug": "jynx",
    "name": "迷唇姐",
    "genus": "人形宝可梦",
    "types": [
      "ice",
      "psychic"
    ],
    "base": {
      "hp": 65,
      "atk": 50,
      "def": 35,
      "spa": 115,
      "spd": 95,
      "spe": 95
    },
    "height": 14,
    "weight": 406
  },
  {
    "id": 125,
    "slug": "electabuzz",
    "name": "电击兽",
    "genus": "电击宝可梦",
    "types": [
      "electric"
    ],
    "base": {
      "hp": 65,
      "atk": 83,
      "def": 57,
      "spa": 95,
      "spd": 85,
      "spe": 105
    },
    "height": 11,
    "weight": 300
  },
  {
    "id": 126,
    "slug": "magmar",
    "name": "鸭嘴火兽",
    "genus": "吐火宝可梦",
    "types": [
      "fire"
    ],
    "base": {
      "hp": 65,
      "atk": 95,
      "def": 57,
      "spa": 100,
      "spd": 85,
      "spe": 93
    },
    "height": 13,
    "weight": 445
  },
  {
    "id": 127,
    "slug": "pinsir",
    "name": "凯罗斯",
    "genus": "锹形虫宝可梦",
    "types": [
      "bug"
    ],
    "base": {
      "hp": 65,
      "atk": 125,
      "def": 100,
      "spa": 55,
      "spd": 70,
      "spe": 85
    },
    "height": 15,
    "weight": 550
  },
  {
    "id": 128,
    "slug": "tauros",
    "name": "肯泰罗",
    "genus": "暴牛宝可梦",
    "types": [
      "normal"
    ],
    "base": {
      "hp": 75,
      "atk": 100,
      "def": 95,
      "spa": 40,
      "spd": 70,
      "spe": 110
    },
    "height": 14,
    "weight": 884
  },
  {
    "id": 129,
    "slug": "magikarp",
    "name": "鲤鱼王",
    "genus": "鱼宝可梦",
    "types": [
      "water"
    ],
    "base": {
      "hp": 20,
      "atk": 10,
      "def": 55,
      "spa": 15,
      "spd": 20,
      "spe": 80
    },
    "height": 9,
    "weight": 100
  },
  {
    "id": 130,
    "slug": "gyarados",
    "name": "暴鲤龙",
    "genus": "凶恶宝可梦",
    "types": [
      "water",
      "flying"
    ],
    "base": {
      "hp": 95,
      "atk": 125,
      "def": 79,
      "spa": 60,
      "spd": 100,
      "spe": 81
    },
    "height": 65,
    "weight": 2350
  },
  {
    "id": 131,
    "slug": "lapras",
    "name": "拉普拉斯",
    "genus": "乘载宝可梦",
    "types": [
      "water",
      "ice"
    ],
    "base": {
      "hp": 130,
      "atk": 85,
      "def": 80,
      "spa": 85,
      "spd": 95,
      "spe": 60
    },
    "height": 25,
    "weight": 2200
  },
  {
    "id": 132,
    "slug": "ditto",
    "name": "百变怪",
    "genus": "变身宝可梦",
    "types": [
      "normal"
    ],
    "base": {
      "hp": 48,
      "atk": 48,
      "def": 48,
      "spa": 48,
      "spd": 48,
      "spe": 48
    },
    "height": 3,
    "weight": 40
  },
  {
    "id": 133,
    "slug": "eevee",
    "name": "伊布",
    "genus": "进化宝可梦",
    "types": [
      "normal"
    ],
    "base": {
      "hp": 55,
      "atk": 55,
      "def": 50,
      "spa": 45,
      "spd": 65,
      "spe": 55
    },
    "height": 3,
    "weight": 65
  },
  {
    "id": 134,
    "slug": "vaporeon",
    "name": "水伊布",
    "genus": "吐泡宝可梦",
    "types": [
      "water"
    ],
    "base": {
      "hp": 130,
      "atk": 65,
      "def": 60,
      "spa": 110,
      "spd": 95,
      "spe": 65
    },
    "height": 10,
    "weight": 290
  },
  {
    "id": 135,
    "slug": "jolteon",
    "name": "雷伊布",
    "genus": "雷宝可梦",
    "types": [
      "electric"
    ],
    "base": {
      "hp": 65,
      "atk": 65,
      "def": 60,
      "spa": 110,
      "spd": 95,
      "spe": 130
    },
    "height": 8,
    "weight": 245
  },
  {
    "id": 136,
    "slug": "flareon",
    "name": "火伊布",
    "genus": "火宝可梦",
    "types": [
      "fire"
    ],
    "base": {
      "hp": 65,
      "atk": 130,
      "def": 60,
      "spa": 95,
      "spd": 110,
      "spe": 65
    },
    "height": 9,
    "weight": 250
  },
  {
    "id": 137,
    "slug": "porygon",
    "name": "多边兽",
    "genus": "虚拟宝可梦",
    "types": [
      "normal"
    ],
    "base": {
      "hp": 65,
      "atk": 60,
      "def": 70,
      "spa": 85,
      "spd": 75,
      "spe": 40
    },
    "height": 8,
    "weight": 365
  },
  {
    "id": 138,
    "slug": "omanyte",
    "name": "菊石兽",
    "genus": "漩涡宝可梦",
    "types": [
      "rock",
      "water"
    ],
    "base": {
      "hp": 35,
      "atk": 40,
      "def": 100,
      "spa": 90,
      "spd": 55,
      "spe": 35
    },
    "height": 4,
    "weight": 75
  },
  {
    "id": 139,
    "slug": "omastar",
    "name": "多刺菊石兽",
    "genus": "漩涡宝可梦",
    "types": [
      "rock",
      "water"
    ],
    "base": {
      "hp": 70,
      "atk": 60,
      "def": 125,
      "spa": 115,
      "spd": 70,
      "spe": 55
    },
    "height": 10,
    "weight": 350
  },
  {
    "id": 140,
    "slug": "kabuto",
    "name": "化石盔",
    "genus": "甲壳宝可梦",
    "types": [
      "rock",
      "water"
    ],
    "base": {
      "hp": 30,
      "atk": 80,
      "def": 90,
      "spa": 55,
      "spd": 45,
      "spe": 55
    },
    "height": 5,
    "weight": 115
  },
  {
    "id": 141,
    "slug": "kabutops",
    "name": "镰刀盔",
    "genus": "甲壳宝可梦",
    "types": [
      "rock",
      "water"
    ],
    "base": {
      "hp": 60,
      "atk": 115,
      "def": 105,
      "spa": 65,
      "spd": 70,
      "spe": 80
    },
    "height": 13,
    "weight": 405
  },
  {
    "id": 142,
    "slug": "aerodactyl",
    "name": "化石翼龙",
    "genus": "化石宝可梦",
    "types": [
      "rock",
      "flying"
    ],
    "base": {
      "hp": 80,
      "atk": 105,
      "def": 65,
      "spa": 60,
      "spd": 75,
      "spe": 130
    },
    "height": 18,
    "weight": 590
  },
  {
    "id": 143,
    "slug": "snorlax",
    "name": "卡比兽",
    "genus": "瞌睡宝可梦",
    "types": [
      "normal"
    ],
    "base": {
      "hp": 160,
      "atk": 110,
      "def": 65,
      "spa": 65,
      "spd": 110,
      "spe": 30
    },
    "height": 21,
    "weight": 4600
  },
  {
    "id": 144,
    "slug": "articuno",
    "name": "急冻鸟",
    "genus": "冰冻宝可梦",
    "types": [
      "ice",
      "flying"
    ],
    "base": {
      "hp": 90,
      "atk": 85,
      "def": 100,
      "spa": 95,
      "spd": 125,
      "spe": 85
    },
    "height": 17,
    "weight": 554
  },
  {
    "id": 145,
    "slug": "zapdos",
    "name": "闪电鸟",
    "genus": "电击宝可梦",
    "types": [
      "electric",
      "flying"
    ],
    "base": {
      "hp": 90,
      "atk": 90,
      "def": 85,
      "spa": 125,
      "spd": 90,
      "spe": 100
    },
    "height": 16,
    "weight": 526
  },
  {
    "id": 146,
    "slug": "moltres",
    "name": "火焰鸟",
    "genus": "火焰宝可梦",
    "types": [
      "fire",
      "flying"
    ],
    "base": {
      "hp": 90,
      "atk": 100,
      "def": 90,
      "spa": 125,
      "spd": 85,
      "spe": 90
    },
    "height": 20,
    "weight": 600
  },
  {
    "id": 147,
    "slug": "dratini",
    "name": "迷你龙",
    "genus": "龙宝可梦",
    "types": [
      "dragon"
    ],
    "base": {
      "hp": 41,
      "atk": 64,
      "def": 45,
      "spa": 50,
      "spd": 50,
      "spe": 50
    },
    "height": 18,
    "weight": 33
  },
  {
    "id": 148,
    "slug": "dragonair",
    "name": "哈克龙",
    "genus": "龙宝可梦",
    "types": [
      "dragon"
    ],
    "base": {
      "hp": 61,
      "atk": 84,
      "def": 65,
      "spa": 70,
      "spd": 70,
      "spe": 70
    },
    "height": 40,
    "weight": 165
  },
  {
    "id": 149,
    "slug": "dragonite",
    "name": "快龙",
    "genus": "龙宝可梦",
    "types": [
      "dragon",
      "flying"
    ],
    "base": {
      "hp": 91,
      "atk": 134,
      "def": 95,
      "spa": 100,
      "spd": 100,
      "spe": 80
    },
    "height": 22,
    "weight": 2100
  },
  {
    "id": 150,
    "slug": "mewtwo",
    "name": "超梦",
    "genus": "基因宝可梦",
    "types": [
      "psychic"
    ],
    "base": {
      "hp": 106,
      "atk": 110,
      "def": 90,
      "spa": 154,
      "spd": 90,
      "spe": 130
    },
    "height": 20,
    "weight": 1220
  },
  {
    "id": 151,
    "slug": "mew",
    "name": "梦幻",
    "genus": "新种宝可梦",
    "types": [
      "psychic"
    ],
    "base": {
      "hp": 100,
      "atk": 100,
      "def": 100,
      "spa": 100,
      "spd": 100,
      "spe": 100
    },
    "height": 4,
    "weight": 40
  }
] as const;

export const KANTO_BY_SLUG: Record<string, DexEntry> = Object.fromEntries(
  KANTO_DEX.map((e) => [e.slug, e]),
);

export const KANTO_BY_ID: Record<number, DexEntry> = Object.fromEntries(
  KANTO_DEX.map((e) => [e.id, e]),
);
